// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy9PJuqCBt46TqEBh0ZyPHteqi-avV4Mo',
    appId: '1:894010278065:web:647498c7434e6e4de7a290',
    messagingSenderId: '894010278065',
    projectId: 'chat-app-736fb',
    authDomain: 'chat-app-736fb.firebaseapp.com',
    storageBucket: 'chat-app-736fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOQlCLQ_p9iG55V8rBiqWKUdTAMTqqhC0',
    appId: '1:894010278065:android:2c27acd5a3430315e7a290',
    messagingSenderId: '894010278065',
    projectId: 'chat-app-736fb',
    storageBucket: 'chat-app-736fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOzDecPtyqPrKwJ673Vsv6ljL1hFD6RtQ',
    appId: '1:894010278065:ios:f5b16fc1c8d7b187e7a290',
    messagingSenderId: '894010278065',
    projectId: 'chat-app-736fb',
    storageBucket: 'chat-app-736fb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

}